set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN P17 [get_ports clk]

set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property PACKAGE_PIN P15 [get_ports rst_n]

set_property IOSTANDARD LVCMOS33 [get_ports octave_button]
set_property PACKAGE_PIN R17 [get_ports octave_button]
    
set_property IOSTANDARD LVCMOS33 [get_ports {key_notes[0]}]
set_property PACKAGE_PIN P5 [get_ports {key_notes[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {key_notes[1]}]
set_property PACKAGE_PIN P4 [get_ports {key_notes[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {key_notes[2]}]
set_property PACKAGE_PIN P3 [get_ports {key_notes[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {key_notes[3]}]
set_property PACKAGE_PIN P2 [get_ports {key_notes[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {key_notes[4]}]
set_property PACKAGE_PIN R2  [get_ports {key_notes[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports {key_notes[5]}]
set_property PACKAGE_PIN M4 [get_ports {key_notes[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports {key_notes[6]}]
set_property PACKAGE_PIN N4 [get_ports {key_notes[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports speaker]
set_property PACKAGE_PIN H17 [get_ports speaker]

set_property IOSTANDARD LVCMOS33 [get_ports set_mode]
set_property PACKAGE_PIN R15 [get_ports set_mode]

set_property IOSTANDARD LVCMOS33 [get_ports set_speed]
set_property PACKAGE_PIN V1 [get_ports set_speed]

set_property IOSTANDARD LVCMOS33 [get_ports set_song]
set_property PACKAGE_PIN R11 [get_ports set_song]

set_property IOSTANDARD LVCMOS33 [get_ports {light[6]}]
set_property PACKAGE_PIN J2 [get_ports {light[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports {light[5]}]
set_property PACKAGE_PIN J3 [get_ports {light[5]}]

set_property IOSTANDARD LVCMOS33 [get_ports {light[4]}]
set_property PACKAGE_PIN H4 [get_ports {light[4]}]

set_property IOSTANDARD LVCMOS33 [get_ports {light[3]}]
set_property PACKAGE_PIN J4 [get_ports {light[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {light[2]}]
set_property PACKAGE_PIN G3 [get_ports {light[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {light[1]}]
set_property PACKAGE_PIN G4 [get_ports {light[1]}]

set_property IOSTANDARD LVCMOS33 [get_ports {light[0]}]
set_property PACKAGE_PIN F6 [get_ports {light[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports tub_sel]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control[0]}]

set_property PACKAGE_PIN G2 [get_ports tub_sel]
set_property PACKAGE_PIN B4 [get_ports {tub_control[7]}]
set_property PACKAGE_PIN A4 [get_ports {tub_control[6]}]
set_property PACKAGE_PIN A3 [get_ports {tub_control[5]}]
set_property PACKAGE_PIN B1 [get_ports {tub_control[4]}]
set_property PACKAGE_PIN A1 [get_ports {tub_control[3]}]
set_property PACKAGE_PIN B3 [get_ports {tub_control[2]}]
set_property PACKAGE_PIN B2 [get_ports {tub_control[1]}]
set_property PACKAGE_PIN D5 [get_ports {tub_control[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property PACKAGE_PIN D7 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports vsync]
set_property PACKAGE_PIN C4 [get_ports vsync]

set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[0]}]
set_property PACKAGE_PIN F5 [get_ports {vga_rgb[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[1]}]
set_property PACKAGE_PIN C6 [get_ports {vga_rgb[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[2]}]
set_property PACKAGE_PIN C5 [get_ports {vga_rgb[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[3]}]
set_property PACKAGE_PIN B7 [get_ports {vga_rgb[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[4]}]
set_property PACKAGE_PIN B6 [get_ports {vga_rgb[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[5]}]
set_property PACKAGE_PIN A6 [get_ports {vga_rgb[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[6]}]
set_property PACKAGE_PIN A5 [get_ports {vga_rgb[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[7]}]
set_property PACKAGE_PIN D8 [get_ports {vga_rgb[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[8]}]
set_property PACKAGE_PIN C7 [get_ports {vga_rgb[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[9]}]
set_property PACKAGE_PIN E6 [get_ports {vga_rgb[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[10]}]
set_property PACKAGE_PIN E5 [get_ports {vga_rgb[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_rgb[11]}]
set_property PACKAGE_PIN E7 [get_ports {vga_rgb[11]}]

set_property PACKAGE_PIN K1 [get_ports {reaction_rate[7]}]
set_property PACKAGE_PIN H6 [get_ports {reaction_rate[6]}]
set_property PACKAGE_PIN H5 [get_ports {reaction_rate[5]}]
set_property PACKAGE_PIN J5 [get_ports {reaction_rate[4]}]
set_property PACKAGE_PIN K6 [get_ports {reaction_rate[3]}]
set_property PACKAGE_PIN L1 [get_ports {reaction_rate[2]}]
set_property PACKAGE_PIN M1 [get_ports {reaction_rate[1]}]
set_property PACKAGE_PIN K3 [get_ports {reaction_rate[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reaction_rate[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reaction_rate[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reaction_rate[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reaction_rate[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reaction_rate[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reaction_rate[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reaction_rate[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {reaction_rate[0]}]

set_property PACKAGE_PIN U4 [get_ports set_user]
set_property PACKAGE_PIN G1 [get_ports  tub_sel_user]
set_property PACKAGE_PIN D4 [get_ports {tub_control_user[7]}]
set_property PACKAGE_PIN E3 [get_ports {tub_control_user[6]}]
set_property PACKAGE_PIN D3 [get_ports {tub_control_user[5]}]
set_property PACKAGE_PIN F4 [get_ports {tub_control_user[4]}]
set_property PACKAGE_PIN F3 [get_ports {tub_control_user[3]}]
set_property PACKAGE_PIN E2 [get_ports {tub_control_user[2]}]
set_property PACKAGE_PIN D2 [get_ports {tub_control_user[1]}]
set_property PACKAGE_PIN H2 [get_ports {tub_control_user[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports set_user]
set_property IOSTANDARD LVCMOS33 [get_ports  tub_sel_user]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_user[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_user[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_user[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_user[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_user[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_user[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_user[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {tub_control_user[0]}]
